services:
  postgres:
    image: postgres:16-alpine
    container_name: fitness_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
      POSTGRES_DB: fitness_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitness_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitness_user -d fitness_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"   # порт для подключения с хоста
    volumes:
      - redis-data:/data  # постоянное хранение данных
    command: [ "redis-server", "--appendonly", "yes" ] # включаем AOF для сохранения данных
    networks:
      - redis-network

volumes:
  postgres_data:
    driver: local
  redis-data:

networks:
  redis-network:
    driver: bridge
  fitness_network:
    driver: bridge